name: LumaGlowAPI
version: '${version}'
description: 'Small plugin to manage glow colors'
author: 'Jsinco'
main: dev.lumas.glowapi.LumaGlowAPI
api-version: '1.20'
folia-supported: true
depend:
  - LumaCore
softdepend:
  - PlaceholderAPI
permissions:
  lumaglowapi.command:
    description: Allows use of the /lumaglowapi command
    default: op
  lumaglowapi.command.update:
    description: Allows use of the /lumaglowapi update command
    default: op
  lumaglowapi.command.colorentity:
    description: Allows use of the /lumaglowapi colorentity command
    default: op
  lumaglowapi.command.pack:
    description: Allows re-sending the glow-effect resource pack
    default: op
    children:
      lumaglowapi.command: true
  lumaglowapi.command.reload:
    description: Allows reloading of the config
    default: op
    children:
      lumaglowapi.command: true
  lumaglowapi.command.color:
    description: Allows use of the /lumaglowapi color command
    default: op
    children:
      lumaglowapi.command: true
  lumaglowapi.command.color.other:
    description: Allows use of colors on other players
    default: op
    children:
      lumaglowapi.command: true
  lumaglowapi.color.all:
    description: Allows use of all colors
    default: op
    children:
      lumaglowapi.color.black: true
      lumaglowapi.color.dark_blue: true
      lumaglowapi.color.dark_green: true
      lumaglowapi.color.dark_aqua: true
      lumaglowapi.color.dark_red: true
      lumaglowapi.color.dark_purple: true
      lumaglowapi.color.gold: true
      lumaglowapi.color.gray: true
      lumaglowapi.color.dark_gray: true
      lumaglowapi.color.blue: true
      lumaglowapi.color.green: true
      lumaglowapi.color.aqua: true
      lumaglowapi.color.red: true
      lumaglowapi.color.light_purple: true
      lumaglowapi.color.yellow: true
      lumaglowapi.color.white: true
      lumaglowapi.color.custom: true
      lumaglowapi.color.preset.rainbow: true
      lumaglowapi.color.preset.rainbow_slow: true
      lumaglowapi.color.preset.rainbow_fast: true
      lumaglowapi.color.preset.fire: true
      lumaglowapi.color.preset.sunset: true
      lumaglowapi.color.preset.forest: true
      lumaglowapi.color.preset.acid: true
      lumaglowapi.color.preset.ocean: true
      lumaglowapi.color.preset.ice: true
      lumaglowapi.color.preset.galaxy: true
      lumaglowapi.color.preset.candy: true
      lumaglowapi.color.preset.pulse_red: true
      lumaglowapi.color.preset.pulse_aqua: true
      lumaglowapi.color.preset.pulse_pink: true
      lumaglowapi.color.preset.pulse_yellow: true
      lumaglowapi.color.preset.mistral: true
      lumaglowapi.color.preset.mistral_slow: true
  lumaglowapi.color.custom:
    description: Allows RGB colors and custom rainbow / gradient / pulse effects
    default: op
  lumaglowapi.color.preset.rainbow:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.rainbow_slow:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.rainbow_fast:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.fire:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.sunset:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.forest:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.acid:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.ocean:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.ice:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.galaxy:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.candy:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.pulse_red:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.pulse_aqua:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.pulse_pink:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.pulse_yellow:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.mistral:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.preset.mistral_slow:
    description: Allows use of a preset
    default: op
  lumaglowapi.color.black:
    description: Allows use of a color
    default: op
  lumaglowapi.color.dark_blue:
    description: Allows use of a color
    default: op
  lumaglowapi.color.dark_green:
    description: Allows use of a color
    default: op
  lumaeglowapi.color.dark_green:
    description: Allows use of a color
    default: op
  lumaglowapi.color.dark_aqua:
    description: Allows use of a color
    default: op
  lumaglowapi.color.dark_red:
    description: Allows use of a color
    default: op
  lumaglowapi.color.dark_purple:
    description: Allows use of a color
    default: op
  lumaglowapi.color.gold:
    description: Allows use of a color
    default: op
  lumaglowapi.color.gray:
    description: Allows use of a color
    default: op
  lumaglowapi.color.dark_gray:
    description: Allows use of a color
    default: op
  lumaglowapi.color.blue:
    description: Allows use of a color
    default: op
  lumaglowapi.color.green:
    description: Allows use of a color
    default: op
  lumaglowapi.color.aqua:
    description: Allows use of a color
    default: op
  lumaglowapi.color.red:
    description: Allows use of a color
    default: op
  lumaglowapi.color.light_purple:
    description: Allows use of a color
    default: op
  lumaglowapi.color.yellow:
    description: Allows use of a color
    default: op
  lumaglowapi.color.white:
    description: Allows use of a color
    default: op